In [1]:
import argparse
from neural_priors.utils.data import Subject
from fit_model import get_paradigm, get_model, fit_model, fit_model_cv
from pathlib import Path
import numpy as np
from braincoder.utils import get_rsq
import pandas as pd
import os
import os.path as op
from braincoder.optimize import ParameterFitter
from braincoder.models import AlphaGaussianPRF
from neural_priors.encoding_model2.models import AlphaDeltaModel
from braincoder.optimize import ResidualFitter
import pingouin as pg

In [13]:
def get_decoding_paradigm(sub, fit_responses=False, drop_levels=True):
        # Get paradigm/data/model
    paradigm = get_paradigm(sub, fit_responses=fit_responses)
    paradigm = paradigm.set_index(pd.Index((paradigm.index.get_level_values('run') - 1) % 4 + 1, name='run2'), append=True)
    paradigm.index = paradigm.index.swaplevel('run', 'run2')
    paradigm = paradigm.astype(np.float32)
    
    if drop_levels:
        paradigm = paradigm.droplevel(['run', 'trial_nr', 'subject'])
    
    return paradigm

# def main(subject, model_label=3, roi='NPCr', bids_folder='/data/ds-neural_priors', smoothed=True, debug=False, fit_responses=False,
#          n_voxels=100):

bids_folder = '/data/ds-neuralpriors'

subject = 1
model_label = 15
debug= True
smoothed = True
fit_responses = False

separate_sigmas = True

roi = 'NPCr'
n_voxels = 100

assert model_label in [15], 'Only model 3, 4 and 5 are supported for decoding'


sub = Subject(subject_id=subject, bids_folder=bids_folder)
bids_folder = Path(bids_folder)

max_n_iterations = 100 if debug else 2000

# Create target folder
key = f'model{model_label}'

if smoothed:
    key += '.smoothed'

if fit_responses:
    key += '.fit_responses'

if separate_sigmas:
    key += '.seperate_sigmas'

target_dir = bids_folder / 'derivatives' / 'decoding2' / key / f'sub-{subject}' / 'func'

if not op.exists(target_dir):
    os.makedirs(target_dir)

# Get paradigm/data/model
paradigm = get_decoding_paradigm(sub, fit_responses=fit_responses)

data = sub.get_single_trial_estimates(session=None, smoothed=smoothed)
masker = sub.get_volume_mask(roi=roi, epi_space=True, return_masker=True)
data = pd.DataFrame(masker.fit_transform(data), index=paradigm.index).astype(np.float32)

# all_cvr2 = []

stimulus_range = np.sort(paradigm['x'].unique())
stimulus_range = np.stack([np.repeat(stimulus_range, 2), np.stack(np.tile([0, 1], len(stimulus_range)), axis=0)], axis=1)

pdfs = []

for (test_session, test_run), _ in paradigm.groupby(level=['session', 'run2']):

    print(f'Fitting using session {test_session} run {test_run} as test set')

    test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)
    train_data, train_paradigm = data.drop((test_session, test_run)).copy(), paradigm.drop((test_session, test_run)).copy()

    print(test_paradigm)

    # Get model
    model = get_model(model_label)

    # Cross-validate to get number of (and which) voxels
    if n_voxels == 0:

        print('Cross-validating to get number of voxels')

        cvr2 = fit_model_cv(train_data, train_paradigm, model_label, max_n_iterations=max_n_iterations)
        print(cvr2)
        r2_mask = cvr2 > 0.0

        target_fn = op.join(target_dir, f'sub-{subject}_ses-{test_session}_run2-{test_run}_mask-{roi}_desc-cvr2_pars.tsv')
        cvr2.to_csv(target_fn, sep='\t')

        print(f'Selecting {np.sum(r2_mask)} voxels with cvr2 > 0.0')

        print(train_data)
        train_data = train_data.loc[:, r2_mask]
        print(train_data)
        test_data = test_data.loc[:, r2_mask]
        gd_pars = fit_model(model_label, model, train_data.loc[:, r2_mask], train_paradigm, max_n_iterations=max_n_iterations)        

    else:

        gd_pars = fit_model(model_label, model, train_data, train_paradigm, max_n_iterations=max_n_iterations)        

        pred = model.predict(paradigm=train_paradigm, parameters=gd_pars)

        r2 = get_rsq(train_data, pred)
        print(r2.describe())

        r2 = r2[r2 < 1.0]
        r2_mask = r2.sort_values(ascending=False).index[:n_voxels]

        gd_pars = gd_pars.loc[r2_mask]
        model.apply_mask(r2_mask)

        train_data = train_data[r2_mask]
        test_data = test_data[r2_mask]


    if separate_sigmas:

        train_narrow_ix = train_paradigm['range'] == 0.0
        train_wide_ix = train_paradigm['range'] == 1.0

        train_data_narrow = train_data[train_narrow_ix]
        train_data_wide = train_data[train_wide_ix]
        train_paradigm_narrow = train_paradigm[train_narrow_ix]
        train_paradigm_wide = train_paradigm[train_wide_ix]

        
        test_narrow_ix = test_paradigm['range'] == 0.0
        test_wide_ix = test_paradigm['range'] == 1.0
        test_data_narrow = test_data[test_narrow_ix]
        test_data_wide = test_data[test_wide_ix]


        stimulus_range_narow = stimulus_range[:len(stimulus_range) // 2]
        stimulus_range_wide = stimulus_range[len(stimulus_range) // 2:]

        # Get pdf for narrow condition
        model.init_pseudoWWT(stimulus_range_narow, gd_pars)

        residfit_narrow = ResidualFitter(model, train_data_narrow,
                                        train_paradigm_narrow, parameters=gd_pars,)
        omega_narrow, dof_narrow = residfit_narrow.fit(init_sigma2=0.1,
                init_dof=10.0,
                method='t',
                learning_rate=0.05,
                max_n_iterations=20000 if not debug else 100)

        print('DOF narrow', dof_narrow)
        pdf_narrow = model.get_stimulus_pdf(test_data_narrow, stimulus_range,
                gd_pars,
                omega=omega_narrow,
                dof=dof_narrow,
                normalize=False)
        

        # Get pdf for wide condition
        model.init_pseudoWWT(stimulus_range_wide, gd_pars)
        residfit_wide = ResidualFitter(model, train_data_wide,
                                        train_paradigm_wide, parameters=gd_pars,)
        omega_wide, dof_wide = residfit_wide.fit(init_sigma2=0.1,
                init_dof=10.0,
                method='t',
                learning_rate=0.05,
                max_n_iterations=20000 if not debug else 100)

        print('DOF wide', dof_wide)
        pdf_wide = model.get_stimulus_pdf(test_data_wide, stimulus_range,
                gd_pars,
                omega=omega_wide,
                dof=dof_wide,
                normalize=False)
        pdfs.append(pd.concat([pdf_narrow, pdf_wide], axis=1))



    else:
        model.init_pseudoWWT(stimulus_range, gd_pars)

        residfit = ResidualFitter(model, train_data,
                                    train_paradigm, parameters=gd_pars,)

        omega, dof = residfit.fit(init_sigma2=0.1,
                init_dof=10.0,
                method='t',
                learning_rate=0.05,
                max_n_iterations=20000 if not debug else 100)

        print('DOF', dof)

        pdf = model.get_stimulus_pdf(test_data, stimulus_range,
                gd_pars,
                omega=omega,
                dof=dof,
                normalize=False)

        print(pdf)
        pdfs.append(pdf)

pdfs = pd.concat(pdfs)        

target_fn = op.join(target_dir, f'sub-{subject}_mask-{roi}_nvoxels-{n_voxels}_pars.tsv')

Fitting using session 1 run 1 as test set
                 x  range
session run2
1       1     11.0    0.0
        1     23.0    0.0
        1     23.0    0.0
        1     22.0    0.0
        1     21.0    0.0
        1     20.0    0.0
        1     10.0    0.0
        1     19.0    0.0
        1     21.0    0.0
        1     18.0    0.0
        1     22.0    0.0
        1     13.0    0.0
        1     20.0    0.0
        1     19.0    0.0
        1     19.0    0.0
        1     20.0    0.0
        1     20.0    0.0
        1     12.0    0.0
        1     12.0    0.0
        1     16.0    0.0
        1     23.0    0.0
        1     10.0    0.0
        1     18.0    0.0
        1     16.0    0.0
        1     11.0    0.0
        1     12.0    0.0
        1     20.0    0.0
        1     17.0    0.0
        1     10.0    0.0
        1     22.0    0.0
        1     28.0    1.0
        1     34.0    1.0
        1     19.0    1.0
        1     33.0    1.0
        1     28.0    1.0
        1     31.0    1.0
        1     10.0    1.0
        1     40.0    1.0
        1     32.0    1.0
        1     27.0    1.0
        1     30.0    1.0
        1     38.0    1.0
        1     31.0    1.0
        1     12.0    1.0
        1     13.0    1.0
        1     33.0    1.0
        1     30.0    1.0
        1     26.0    1.0
        1     23.0    1.0
        1     38.0    1.0
        1     24.0    1.0
        1     37.0    1.0
        1     39.0    1.0
        1     38.0    1.0
        1     15.0    1.0
        1     19.0    1.0
        1     29.0    1.0
        1     13.0    1.0
        1     10.0    1.0
        1     19.0    1.0
7
['mu_narrow', 'delta_wide', 'lower_bound_range', 'baseline', 'sd_narrow', 'sd_wide_scale', 'amplitude']
7
(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45.]), [2.0], [10.0], array([0.], dtype=float32), array([0.69314718, 0.78652822, 0.87990926, 0.9732903 , 1.06667135,
       1.16005239, 1.25343343, 1.34681447, 1.44019551, 1.53357655,
       1.62695759, 1.72033864, 1.81371968, 1.90710072, 2.00048176,
       2.0938628 , 2.18724384, 2.28062488, 2.37400593, 2.46738697,
       2.56076801, 2.65414905, 2.74753009, 2.84091113, 2.93429217,
       3.02767322, 3.12105426, 3.2144353 , 3.30781634, 3.40119738]), [1.0], array([1.], dtype=float32))
Working with chunk size of 2058
Using correlation cost!

/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)
/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)

  0%|          | 0/1 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

*** Fitting: ***
 * mu_narrow
 * baseline
 * sd_narrow
 * sd_wide_scale
 * amplitude
*** Fixed Parameters: ***
 * lower_bound_range
 * delta_wide
*** Shared Parameters: ***
 * sd_wide_scale
Number of problematic voxels (mask): 0
Number of voxels remaining (mask): 771

Current R2: -0.01686/Best R2: -0.01686: 100%|██████████| 100/100 [00:01<00:00, 62.30it/s]
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

count    771.000000
mean      -0.016858
std        0.046994
min       -0.325127
25%       -0.018113
50%       -0.000246
75%        0.005390
max        0.063019
Name: r2, dtype: float64
init_tau: 0.32297563552856445, 1.426098346710205
USING A PSEUDO-WWT!
WWT max: 37.10054016113281

  0%|          | 0/100 [00:00<?, ?it/s]

DOF narrow 9.282441

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

init_tau: 0.3328811228275299, 1.4631608724594116
USING A PSEUDO-WWT!
WWT max: 32.798561096191406

  0%|          | 0/100 [00:00<?, ?it/s]

DOF wide 8.000766
Fitting using session 1 run 2 as test set
                 x  range
session run2
1       2     11.0    0.0
        2     18.0    0.0
        2     24.0    0.0
        2     17.0    0.0
        2     17.0    0.0
        2     17.0    0.0
        2     10.0    0.0
        2     20.0    0.0
        2     16.0    0.0
        2     25.0    0.0
        2     21.0    0.0
        2     13.0    0.0
        2     24.0    0.0
        2     10.0    0.0
        2     18.0    0.0
        2     10.0    0.0
        2     24.0    0.0
        2     19.0    0.0
        2     17.0    0.0
        2     13.0    0.0
        2     22.0    0.0
        2     22.0    0.0
        2     24.0    0.0
        2     21.0    0.0
        2     10.0    0.0
        2     20.0    0.0
        2     10.0    0.0
        2     19.0    0.0
        2     15.0    0.0
        2     25.0    0.0
        2     33.0    1.0
        2     38.0    1.0
        2     29.0    1.0
        2     20.0    1.0
        2     15.0    1.0
        2     14.0    1.0
        2     13.0    1.0
        2     11.0    1.0
        2     30.0    1.0
        2     10.0    1.0
        2     35.0    1.0
        2     39.0    1.0
        2     36.0    1.0
        2     24.0    1.0
        2     21.0    1.0
        2     20.0    1.0
        2     29.0    1.0
        2     17.0    1.0
        2     20.0    1.0
        2     15.0    1.0
        2     19.0    1.0
        2     20.0    1.0
        2     31.0    1.0
        2     14.0    1.0
        2     25.0    1.0
        2     10.0    1.0
        2     24.0    1.0
        2     37.0    1.0
        2     38.0    1.0
        2     34.0    1.0
7
['mu_narrow', 'delta_wide', 'lower_bound_range', 'baseline', 'sd_narrow', 'sd_wide_scale', 'amplitude']
7
(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45.]), [2.0], [10.0], array([0.], dtype=float32), array([0.69314718, 0.78652822, 0.87990926, 0.9732903 , 1.06667135,
       1.16005239, 1.25343343, 1.34681447, 1.44019551, 1.53357655,
       1.62695759, 1.72033864, 1.81371968, 1.90710072, 2.00048176,
       2.0938628 , 2.18724384, 2.28062488, 2.37400593, 2.46738697,
       2.56076801, 2.65414905, 2.74753009, 2.84091113, 2.93429217,
       3.02767322, 3.12105426, 3.2144353 , 3.30781634, 3.40119738]), [1.0], array([1.], dtype=float32))
Working with chunk size of 2058
Using correlation cost!

/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)
/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)

  0%|          | 0/1 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

*** Fitting: ***
 * mu_narrow
 * baseline
 * sd_narrow
 * sd_wide_scale
 * amplitude
*** Fixed Parameters: ***
 * lower_bound_range
 * delta_wide
*** Shared Parameters: ***
 * sd_wide_scale
Number of problematic voxels (mask): 0
Number of voxels remaining (mask): 771

Current R2: -0.01194/Best R2: -0.01194: 100%|██████████| 100/100 [00:01<00:00, 67.92it/s]
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

count    771.000000
mean      -0.011939
std        0.043827
min       -0.306869
25%       -0.008651
50%        0.001860
75%        0.006372
max        0.072784
Name: r2, dtype: float64
init_tau: 0.317765474319458, 1.3881754875183105
USING A PSEUDO-WWT!
WWT max: 28.60154914855957

  0%|          | 0/100 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

DOF narrow 9.639217
init_tau: 0.3466615676879883, 1.4366884231567383
USING A PSEUDO-WWT!
WWT max: 24.158288955688477

  0%|          | 0/100 [00:00<?, ?it/s]

DOF wide 8.180555
Fitting using session 1 run 3 as test set
                 x  range
session run2
1       3     11.0    0.0
        3     12.0    0.0
        3     17.0    0.0
        3     10.0    0.0
        3     24.0    0.0
        3     20.0    0.0
        3     17.0    0.0
        3     15.0    0.0
        3     17.0    0.0
        3     25.0    0.0
        3     18.0    0.0
        3     14.0    0.0
        3     12.0    0.0
        3     11.0    0.0
        3     16.0    0.0
        3     10.0    0.0
        3     15.0    0.0
        3     18.0    0.0
        3     10.0    0.0
        3     23.0    0.0
        3     25.0    0.0
        3     17.0    0.0
        3     24.0    0.0
        3     18.0    0.0
        3     25.0    0.0
        3     11.0    0.0
        3     13.0    0.0
        3     25.0    0.0
        3     19.0    0.0
        3     13.0    0.0
        3     29.0    1.0
        3     20.0    1.0
        3     12.0    1.0
        3     13.0    1.0
        3     21.0    1.0
        3     22.0    1.0
        3     22.0    1.0
        3     16.0    1.0
        3     10.0    1.0
        3     10.0    1.0
        3     21.0    1.0
        3     35.0    1.0
        3     38.0    1.0
        3     35.0    1.0
        3     31.0    1.0
        3     21.0    1.0
        3     36.0    1.0
        3     25.0    1.0
        3     25.0    1.0
        3     11.0    1.0
        3     31.0    1.0
        3     13.0    1.0
        3     22.0    1.0
        3     25.0    1.0
        3     19.0    1.0
        3     38.0    1.0
        3     11.0    1.0
        3     24.0    1.0
        3     23.0    1.0
        3     26.0    1.0
7
['mu_narrow', 'delta_wide', 'lower_bound_range', 'baseline', 'sd_narrow', 'sd_wide_scale', 'amplitude']
7
(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45.]), [2.0], [10.0], array([0.], dtype=float32), array([0.69314718, 0.78652822, 0.87990926, 0.9732903 , 1.06667135,
       1.16005239, 1.25343343, 1.34681447, 1.44019551, 1.53357655,
       1.62695759, 1.72033864, 1.81371968, 1.90710072, 2.00048176,
       2.0938628 , 2.18724384, 2.28062488, 2.37400593, 2.46738697,
       2.56076801, 2.65414905, 2.74753009, 2.84091113, 2.93429217,
       3.02767322, 3.12105426, 3.2144353 , 3.30781634, 3.40119738]), [1.0], array([1.], dtype=float32))
Working with chunk size of 2058
Using correlation cost!

/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)
/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)

  0%|          | 0/1 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

*** Fitting: ***
 * mu_narrow
 * baseline
 * sd_narrow
 * sd_wide_scale
 * amplitude
*** Fixed Parameters: ***
 * lower_bound_range
 * delta_wide
*** Shared Parameters: ***
 * sd_wide_scale
Number of problematic voxels (mask): 0
Number of voxels remaining (mask): 771

Current R2: -0.01893/Best R2: -0.01893: 100%|██████████| 100/100 [00:01<00:00, 70.15it/s]
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

count    771.000000
mean      -0.018930
std        0.053521
min       -0.367886
25%       -0.022080
50%       -0.000675
75%        0.006460
max        0.077239
Name: r2, dtype: float64
init_tau: 0.33678388595581055, 1.3943582773208618
USING A PSEUDO-WWT!
WWT max: 38.57220458984375

  0%|          | 0/100 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

DOF narrow 9.295383
init_tau: 0.327066034078598, 1.3956818580627441
USING A PSEUDO-WWT!
WWT max: 26.868803024291992

  0%|          | 0/100 [00:00<?, ?it/s]

DOF wide 8.6822195
Fitting using session 1 run 4 as test set
                 x  range
session run2
1       4     13.0    0.0
        4     18.0    0.0
        4     19.0    0.0
        4     18.0    0.0
        4     25.0    0.0
        4     14.0    0.0
        4     20.0    0.0
        4     10.0    0.0
        4     18.0    0.0
        4     20.0    0.0
        4     18.0    0.0
        4     25.0    0.0
        4     21.0    0.0
        4     25.0    0.0
        4     22.0    0.0
        4     17.0    0.0
        4     16.0    0.0
        4     16.0    0.0
        4     12.0    0.0
        4     19.0    0.0
        4     11.0    0.0
        4     25.0    0.0
        4     18.0    0.0
        4     25.0    0.0
        4     17.0    0.0
        4     14.0    0.0
        4     16.0    0.0
        4     17.0    0.0
        4     23.0    0.0
        4     10.0    0.0
        4     22.0    1.0
        4     39.0    1.0
        4     21.0    1.0
        4     21.0    1.0
        4     11.0    1.0
        4     20.0    1.0
        4     23.0    1.0
        4     19.0    1.0
        4     15.0    1.0
        4     38.0    1.0
        4     16.0    1.0
        4     12.0    1.0
        4     28.0    1.0
        4     13.0    1.0
        4     27.0    1.0
        4     13.0    1.0
        4     18.0    1.0
        4     37.0    1.0
        4     19.0    1.0
        4     20.0    1.0
        4     38.0    1.0
        4     17.0    1.0
        4     39.0    1.0
        4     17.0    1.0
        4     31.0    1.0
        4     37.0    1.0
        4     37.0    1.0
        4     22.0    1.0
        4     28.0    1.0
        4     27.0    1.0
7
['mu_narrow', 'delta_wide', 'lower_bound_range', 'baseline', 'sd_narrow', 'sd_wide_scale', 'amplitude']
7
(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45.]), [2.0], [10.0], array([0.], dtype=float32), array([0.69314718, 0.78652822, 0.87990926, 0.9732903 , 1.06667135,
       1.16005239, 1.25343343, 1.34681447, 1.44019551, 1.53357655,
       1.62695759, 1.72033864, 1.81371968, 1.90710072, 2.00048176,
       2.0938628 , 2.18724384, 2.28062488, 2.37400593, 2.46738697,
       2.56076801, 2.65414905, 2.74753009, 2.84091113, 2.93429217,
       3.02767322, 3.12105426, 3.2144353 , 3.30781634, 3.40119738]), [1.0], array([1.], dtype=float32))
Working with chunk size of 2058
Using correlation cost!

/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)
/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)

  0%|          | 0/1 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

*** Fitting: ***
 * mu_narrow
 * baseline
 * sd_narrow
 * sd_wide_scale
 * amplitude
*** Fixed Parameters: ***
 * lower_bound_range
 * delta_wide
*** Shared Parameters: ***
 * sd_wide_scale
Number of problematic voxels (mask): 0
Number of voxels remaining (mask): 771

Current R2: -0.02071/Best R2: -0.02071: 100%|██████████| 100/100 [00:01<00:00, 71.21it/s]

count    771.000000
mean      -0.020706
std        0.051276
min       -0.386964
25%       -0.027614
50%       -0.000139
75%        0.004245
max        0.091645
Name: r2, dtype: float64
WARNING:tensorflow:5 out of the last 8 calls to <function LinearScalingModel._basis_predictions_without_amplitude at 0x30b5ba280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 8 calls to <function LinearScalingModel._basis_predictions_without_amplitude at 0x30b5ba280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

init_tau: 0.3355732560157776, 1.777883529663086
USING A PSEUDO-WWT!
WWT max: 36.52534103393555

  0%|          | 0/100 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

DOF narrow 9.143187
init_tau: 0.3159486949443817, 1.6668299436569214
USING A PSEUDO-WWT!
WWT max: 31.661474227905273

  0%|          | 0/100 [00:00<?, ?it/s]

DOF wide 8.79537
Fitting using session 2 run 1 as test set
                 x  range
session run2
2       1     34.0    1.0
        1     17.0    1.0
        1     10.0    1.0
        1     15.0    1.0
        1     15.0    1.0
        1     15.0    1.0
        1     11.0    1.0
        1     32.0    1.0
        1     29.0    1.0
        1     21.0    1.0
        1     32.0    1.0
        1     27.0    1.0
        1     24.0    1.0
        1     17.0    1.0
        1     32.0    1.0
        1     36.0    1.0
        1     36.0    1.0
        1     17.0    1.0
        1     27.0    1.0
        1     19.0    1.0
        1     12.0    1.0
        1     34.0    1.0
        1     13.0    1.0
        1     19.0    1.0
        1     23.0    1.0
        1     32.0    1.0
        1     21.0    1.0
        1     18.0    1.0
        1     18.0    1.0
        1     15.0    1.0
        1     16.0    0.0
        1     15.0    0.0
        1     15.0    0.0
        1     14.0    0.0
        1     24.0    0.0
        1     22.0    0.0
        1     15.0    0.0
        1     22.0    0.0
        1     19.0    0.0
        1     12.0    0.0
        1     15.0    0.0
        1     14.0    0.0
        1     13.0    0.0
        1     23.0    0.0
        1     25.0    0.0
        1     20.0    0.0
        1     17.0    0.0
        1     16.0    0.0
        1     15.0    0.0
        1     25.0    0.0
        1     16.0    0.0
        1     19.0    0.0
        1     14.0    0.0
        1     10.0    0.0
        1     25.0    0.0
        1     21.0    0.0
        1     25.0    0.0
        1     18.0    0.0
        1     15.0    0.0
        1     18.0    0.0
7
['mu_narrow', 'delta_wide', 'lower_bound_range', 'baseline', 'sd_narrow', 'sd_wide_scale', 'amplitude']
7
(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45.]), [2.0], [10.0], array([0.], dtype=float32), array([0.69314718, 0.78652822, 0.87990926, 0.9732903 , 1.06667135,
       1.16005239, 1.25343343, 1.34681447, 1.44019551, 1.53357655,
       1.62695759, 1.72033864, 1.81371968, 1.90710072, 2.00048176,
       2.0938628 , 2.18724384, 2.28062488, 2.37400593, 2.46738697,
       2.56076801, 2.65414905, 2.74753009, 2.84091113, 2.93429217,
       3.02767322, 3.12105426, 3.2144353 , 3.30781634, 3.40119738]), [1.0], array([1.], dtype=float32))
Working with chunk size of 2058
Using correlation cost!

/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)
/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)

  0%|          | 0/1 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

*** Fitting: ***
 * mu_narrow
 * baseline
 * sd_narrow
 * sd_wide_scale
 * amplitude
*** Fixed Parameters: ***
 * lower_bound_range
 * delta_wide
*** Shared Parameters: ***
 * sd_wide_scale
Number of problematic voxels (mask): 0
Number of voxels remaining (mask): 771

Current R2: -0.01705/Best R2: -0.01705: 100%|██████████| 100/100 [00:01<00:00, 65.65it/s]

count    771.000000
mean      -0.017047
std        0.051554
min       -0.486855
25%       -0.020798
50%        0.000681
75%        0.004638
max        0.067565
Name: r2, dtype: float64
WARNING:tensorflow:6 out of the last 10 calls to <function LinearScalingModel._basis_predictions_without_amplitude at 0x30b578af0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:6 out of the last 10 calls to <function LinearScalingModel._basis_predictions_without_amplitude at 0x30b578af0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

init_tau: 0.33293774724006653, 1.4441415071487427
USING A PSEUDO-WWT!
WWT max: 37.7240104675293

  0%|          | 0/100 [00:00<?, ?it/s]

DOF narrow 10.448075
WARNING:tensorflow:5 out of the last 9 calls to <function EncodingModel._likelihood at 0x30d864dc0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:5 out of the last 9 calls to <function EncodingModel._likelihood at 0x30d864dc0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

init_tau: 0.3266029953956604, 1.4836392402648926
USING A PSEUDO-WWT!
WWT max: 33.33988571166992

  0%|          | 0/100 [00:00<?, ?it/s]

DOF wide 7.8363934
Fitting using session 2 run 2 as test set
                 x  range
session run2
2       2     22.0    1.0
        2     27.0    1.0
        2     14.0    1.0
        2     21.0    1.0
        2     39.0    1.0
        2     24.0    1.0
        2     18.0    1.0
        2     15.0    1.0
        2     29.0    1.0
        2     30.0    1.0
        2     23.0    1.0
        2     29.0    1.0
        2     35.0    1.0
        2     16.0    1.0
        2     32.0    1.0
        2     16.0    1.0
        2     37.0    1.0
        2     22.0    1.0
        2     16.0    1.0
        2     37.0    1.0
        2     11.0    1.0
        2     12.0    1.0
        2     21.0    1.0
        2     19.0    1.0
        2     10.0    1.0
        2     21.0    1.0
        2     40.0    1.0
        2     27.0    1.0
        2     22.0    1.0
        2     23.0    1.0
        2     19.0    0.0
        2     25.0    0.0
        2     12.0    0.0
        2     21.0    0.0
        2     20.0    0.0
        2     16.0    0.0
        2     23.0    0.0
        2     13.0    0.0
        2     17.0    0.0
        2     15.0    0.0
        2     21.0    0.0
        2     18.0    0.0
        2     13.0    0.0
        2     14.0    0.0
        2     23.0    0.0
        2     17.0    0.0
        2     12.0    0.0
        2     10.0    0.0
        2     10.0    0.0
        2     20.0    0.0
        2     21.0    0.0
        2     11.0    0.0
        2     16.0    0.0
        2     11.0    0.0
        2     18.0    0.0
        2     12.0    0.0
        2     14.0    0.0
        2     21.0    0.0
        2     18.0    0.0
        2     23.0    0.0
7
['mu_narrow', 'delta_wide', 'lower_bound_range', 'baseline', 'sd_narrow', 'sd_wide_scale', 'amplitude']
7
(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45.]), [2.0], [10.0], array([0.], dtype=float32), array([0.69314718, 0.78652822, 0.87990926, 0.9732903 , 1.06667135,
       1.16005239, 1.25343343, 1.34681447, 1.44019551, 1.53357655,
       1.62695759, 1.72033864, 1.81371968, 1.90710072, 2.00048176,
       2.0938628 , 2.18724384, 2.28062488, 2.37400593, 2.46738697,
       2.56076801, 2.65414905, 2.74753009, 2.84091113, 2.93429217,
       3.02767322, 3.12105426, 3.2144353 , 3.30781634, 3.40119738]), [1.0], array([1.], dtype=float32))
Working with chunk size of 2058
Using correlation cost!

/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)
/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)

  0%|          | 0/1 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

*** Fitting: ***
 * mu_narrow
 * baseline
 * sd_narrow
 * sd_wide_scale
 * amplitude
*** Fixed Parameters: ***
 * lower_bound_range
 * delta_wide
*** Shared Parameters: ***
 * sd_wide_scale
Number of problematic voxels (mask): 0
Number of voxels remaining (mask): 771

Current R2: -0.01726/Best R2: -0.01726: 100%|██████████| 100/100 [00:01<00:00, 64.86it/s]
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

count    771.000000
mean      -0.017258
std        0.042174
min       -0.335215
25%       -0.023127
50%       -0.000304
75%        0.003960
max        0.053973
Name: r2, dtype: float64
init_tau: 0.2919521927833557, 1.3281000852584839
USING A PSEUDO-WWT!
WWT max: 37.163482666015625

  0%|          | 0/100 [00:00<?, ?it/s]

DOF narrow 8.980229
WARNING:tensorflow:6 out of the last 11 calls to <function EncodingModel._likelihood at 0x30ab0ca60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:6 out of the last 11 calls to <function EncodingModel._likelihood at 0x30ab0ca60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

init_tau: 0.31117743253707886, 1.530430793762207
USING A PSEUDO-WWT!
WWT max: 33.75130081176758

  0%|          | 0/100 [00:00<?, ?it/s]

DOF wide 7.8939643
Fitting using session 2 run 3 as test set
                 x  range
session run2
2       3     29.0    1.0
        3     39.0    1.0
        3     11.0    1.0
        3     11.0    1.0
        3     38.0    1.0
        3     37.0    1.0
        3     39.0    1.0
        3     29.0    1.0
        3     24.0    1.0
        3     21.0    1.0
        3     37.0    1.0
        3     25.0    1.0
        3     40.0    1.0
        3     13.0    1.0
        3     11.0    1.0
        3     40.0    1.0
        3     34.0    1.0
        3     11.0    1.0
        3     16.0    1.0
        3     17.0    1.0
        3     31.0    1.0
        3     29.0    1.0
        3     16.0    1.0
        3     40.0    1.0
        3     19.0    1.0
        3     11.0    1.0
        3     34.0    1.0
        3     21.0    1.0
        3     10.0    1.0
        3     31.0    1.0
        3     20.0    0.0
        3     25.0    0.0
        3     23.0    0.0
        3     11.0    0.0
        3     11.0    0.0
        3     22.0    0.0
        3     20.0    0.0
        3     24.0    0.0
        3     22.0    0.0
        3     19.0    0.0
        3     12.0    0.0
        3     14.0    0.0
        3     20.0    0.0
        3     19.0    0.0
        3     24.0    0.0
        3     20.0    0.0
        3     14.0    0.0
        3     20.0    0.0
        3     14.0    0.0
        3     10.0    0.0
        3     23.0    0.0
        3     15.0    0.0
        3     16.0    0.0
        3     16.0    0.0
        3     14.0    0.0
        3     17.0    0.0
        3     17.0    0.0
        3     25.0    0.0
        3     16.0    0.0
        3     20.0    0.0
7
['mu_narrow', 'delta_wide', 'lower_bound_range', 'baseline', 'sd_narrow', 'sd_wide_scale', 'amplitude']
7
(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45.]), [2.0], [10.0], array([0.], dtype=float32), array([0.69314718, 0.78652822, 0.87990926, 0.9732903 , 1.06667135,
       1.16005239, 1.25343343, 1.34681447, 1.44019551, 1.53357655,
       1.62695759, 1.72033864, 1.81371968, 1.90710072, 2.00048176,
       2.0938628 , 2.18724384, 2.28062488, 2.37400593, 2.46738697,
       2.56076801, 2.65414905, 2.74753009, 2.84091113, 2.93429217,
       3.02767322, 3.12105426, 3.2144353 , 3.30781634, 3.40119738]), [1.0], array([1.], dtype=float32))
Working with chunk size of 2058
Using correlation cost!

/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)
/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)

  0%|          | 0/1 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

*** Fitting: ***
 * mu_narrow
 * baseline
 * sd_narrow
 * sd_wide_scale
 * amplitude
*** Fixed Parameters: ***
 * lower_bound_range
 * delta_wide
*** Shared Parameters: ***
 * sd_wide_scale
Number of problematic voxels (mask): 0
Number of voxels remaining (mask): 771

Current R2: -0.02322/Best R2: -0.02322: 100%|██████████| 100/100 [00:01<00:00, 67.89it/s]
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

count    771.000000
mean      -0.023217
std        0.058052
min       -0.634952
25%       -0.025114
50%       -0.000690
75%        0.002746
max        0.057865
Name: r2, dtype: float64
init_tau: 0.301175981760025, 1.4041568040847778
USING A PSEUDO-WWT!
WWT max: 36.60717010498047

  0%|          | 0/100 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

DOF narrow 9.84682
init_tau: 0.3336021304130554, 1.5130702257156372
USING A PSEUDO-WWT!
WWT max: 28.030597686767578

  0%|          | 0/100 [00:00<?, ?it/s]

DOF wide 8.62281
Fitting using session 2 run 4 as test set
                 x  range
session run2
2       4     15.0    1.0
        4     15.0    1.0
        4     21.0    1.0
        4     39.0    1.0
        4     28.0    1.0
        4     38.0    1.0
        4     19.0    1.0
        4     34.0    1.0
        4     30.0    1.0
        4     25.0    1.0
        4     28.0    1.0
        4     36.0    1.0
        4     22.0    1.0
        4     14.0    1.0
        4     12.0    1.0
        4     34.0    1.0
        4     37.0    1.0
        4     28.0    1.0
        4     34.0    1.0
        4     39.0    1.0
        4     28.0    1.0
        4     23.0    1.0
        4     24.0    1.0
        4     38.0    1.0
        4     40.0    1.0
        4     39.0    1.0
        4     28.0    1.0
        4     35.0    1.0
        4     17.0    1.0
        4     23.0    1.0
        4     24.0    0.0
        4     24.0    0.0
        4     20.0    0.0
        4     22.0    0.0
        4     10.0    0.0
        4     10.0    0.0
        4     11.0    0.0
        4     13.0    0.0
        4     16.0    0.0
        4     12.0    0.0
        4     15.0    0.0
        4     22.0    0.0
        4     12.0    0.0
        4     13.0    0.0
        4     24.0    0.0
        4     16.0    0.0
        4     18.0    0.0
        4     25.0    0.0
        4     16.0    0.0
        4     18.0    0.0
        4     22.0    0.0
        4     21.0    0.0
        4     17.0    0.0
        4     11.0    0.0
        4     18.0    0.0
        4     12.0    0.0
        4     13.0    0.0
        4     18.0    0.0
        4     14.0    0.0
        4     17.0    0.0
7
['mu_narrow', 'delta_wide', 'lower_bound_range', 'baseline', 'sd_narrow', 'sd_wide_scale', 'amplitude']
7
(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45.]), [2.0], [10.0], array([0.], dtype=float32), array([0.69314718, 0.78652822, 0.87990926, 0.9732903 , 1.06667135,
       1.16005239, 1.25343343, 1.34681447, 1.44019551, 1.53357655,
       1.62695759, 1.72033864, 1.81371968, 1.90710072, 2.00048176,
       2.0938628 , 2.18724384, 2.28062488, 2.37400593, 2.46738697,
       2.56076801, 2.65414905, 2.74753009, 2.84091113, 2.93429217,
       3.02767322, 3.12105426, 3.2144353 , 3.30781634, 3.40119738]), [1.0], array([1.], dtype=float32))
Working with chunk size of 2058
Using correlation cost!

/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)
/var/folders/d4/cpqhwlbn301clph1qk64k01nmjkty3/T/ipykernel_52495/151567345.py:72: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_data, test_paradigm = data.loc[(test_session, test_run)].copy().astype(np.float32), paradigm.loc[(test_session, test_run)].copy().astype(np.float32)

  0%|          | 0/1 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

*** Fitting: ***
 * mu_narrow
 * baseline
 * sd_narrow
 * sd_wide_scale
 * amplitude
*** Fixed Parameters: ***
 * lower_bound_range
 * delta_wide
*** Shared Parameters: ***
 * sd_wide_scale
Number of problematic voxels (mask): 0
Number of voxels remaining (mask): 771

Current R2: -0.02119/Best R2: -0.02119: 100%|██████████| 100/100 [00:01<00:00, 68.22it/s]
WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

count    771.000000
mean      -0.021185
std        0.048520
min       -0.397141
25%       -0.026627
50%       -0.000823
75%        0.002839
max        0.047612
Name: r2, dtype: float64
init_tau: 0.2872438132762909, 1.0112258195877075
USING A PSEUDO-WWT!
WWT max: 36.044063568115234

  0%|          | 0/100 [00:00<?, ?it/s]

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

DOF narrow 9.938117
init_tau: 0.3280123770236969, 1.201945424079895
USING A PSEUDO-WWT!
WWT max: 31.862911224365234

  0%|          | 0/100 [00:00<?, ?it/s]

DOF wide 8.662491

In [12]:
test_data

                   305       303       306       367       370       250  \
session run2
1       1     1.287796  1.625972  0.984352  1.427470  1.153153  0.874286
        1     0.143345 -0.170333  0.319031 -0.029559  0.377120  0.298203
        1     0.074736 -0.287898  0.417389 -0.232064  0.509764 -0.150329
        1     0.595963  1.121234  0.626036  0.863480  0.961999  0.547039
        1    -0.291656 -0.437774 -0.068384 -0.536488 -0.031253 -0.085293
        1     1.175819  1.112644  0.763139  0.977652  0.704096  0.810695
        1     1.221768  0.994029  1.268314  0.284468  1.105377  1.185056
        1     0.555407  0.955407  0.708430  0.432017  0.703367  0.653574
        1     0.306929  0.109070  0.204743  0.194848  0.272603  0.046067
        1     0.984464  1.476715  0.686375  1.004672  0.625522  1.168666
        1     0.172300  0.340128  0.352709  0.144116  0.577287  0.242986
        1     0.881557  0.959119  1.104026  0.628215  1.146143  0.835685
        1     0.449823  0.932847  0.199518  0.840682  0.357824  0.297236
        1     0.738084  0.959410  0.409329  0.546015  0.312918  0.529720
        1     0.534251  0.746422  0.568009  0.621244  0.369152  0.412627
        1     0.384643  0.332197  0.682318  0.454676  0.657758  0.511467
        1     0.257693  0.252783  0.272186  0.207689  0.362468 -0.033134
        1     0.797720  1.008544  0.682813  0.886306  0.509117  0.853747
        1     1.051883  1.450676  0.846555  1.105214  0.816989  0.774844
        1    -0.335387 -0.007068 -0.128888 -0.126304  0.036381 -0.051034
        1    -0.494056 -0.183519 -0.183319 -0.405236 -0.199248 -0.134228
        1     1.472028  1.973662  0.945949  1.268547  1.048090  1.188596
        1     1.010452  1.046654  1.005807  0.804984  1.156545  0.731355
        1     1.320459  1.356954  0.433607  1.244782  0.400671  0.927516
        1     0.864970  1.141088  1.087802  0.816602  1.132636  1.255866
        1     1.355256  1.675350  0.780994  0.849053  0.756254  0.986070
        1     0.286469  0.103492  0.793660 -0.214517  0.733670  0.232677
        1     0.371193  0.821044  0.472210  0.325298  0.527548  0.406261
        1     0.149280 -0.113466  0.429181 -0.151856  0.607100  0.010801
        1     0.705833  0.793760  0.342233  0.611413  0.368185  0.108908
        1     1.341627  1.334216  1.158091  1.017394  1.238012  1.116425
        1     1.800111  2.506956  1.116650  1.794717  1.200947  1.477687
        1     1.405220  1.648010  0.885599  1.163713  0.945010  0.876489
        1     1.232476  1.541272  1.320038  1.176172  1.254829  1.463043
        1     0.608760  0.725447  0.714411  0.660101  0.666265  0.533197
        1     0.289772  0.587097  0.529025  0.342043  0.349850  0.587051
        1     1.171387  1.227339  0.859101  0.891187  0.907629  0.842900
        1    -0.113029  0.119395 -0.131485 -0.007186  0.053215 -0.107346
        1     0.568769  0.866851  0.605352  0.430043  0.577604  0.764169
        1     0.357770  0.133970  0.559820  0.133133  0.636198  0.142288
        1     1.015305  0.977302  0.946087  0.612929  1.018590  0.889698
        1     0.212707  0.312247  0.443731  0.243779  0.750811  0.226281
        1     1.641268  1.959699  1.094088  1.409263  1.315691  1.296440
        1     0.577431  0.807599  0.804376  0.617737  0.468761  0.666257
        1     0.481964  0.606543  0.833054  0.201353  0.739713  0.962316
        1    -0.369935  0.090738 -0.578028  0.299648 -0.566498 -0.050594
        1     0.292926  0.530276  0.183956  0.456805  0.245608 -0.101664
        1     0.667792  1.290681  0.191125  0.965677  0.285354  0.150045
        1     0.976252  1.022984  0.829812  0.665735  0.786845  0.897066
        1    -0.113303 -0.129904  0.167571  0.140346  0.349765 -0.188613
        1    -0.000078 -0.040304  0.180648 -0.220292  0.317654  0.051238
        1    -0.452465 -0.537918  0.156734 -0.786529 -0.078618 -0.133606
        1     0.615050  0.796122  0.706548  0.676318  0.828935  0.377711
        1     0.773566  0.808293  0.564118  0.596243  0.396996  0.941845
        1     0.563860  0.828236  0.792932  0.317439  0.699193  0.646811
        1     0.488694  0.690198  0.286713  0.505273  0.377343  0.380960
        1     0.977285  1.040680  0.988219  0.664469  1.092106  0.932458
        1     1.221782  1.271368  0.927890  1.119878  1.395693  0.643805
        1     0.860320  0.835197  0.560308  1.024876  0.829055  0.163421
        1     1.137780  0.869891  0.741945  0.600990  0.952488  0.840336

                   249       301       369       155  ...       643       145  \
session run2                                          ...
1       1     1.126312  1.573675  0.343379 -0.580780  ...  0.327918  0.388739
        1     0.017589 -0.079978  0.295382  0.105468  ... -0.008512 -0.023069
        1    -0.048992 -0.252929 -0.112965 -0.117545  ...  0.538673 -0.159223
        1     0.788464  1.589159  0.507283  1.398744  ...  0.111735  0.375293
        1    -0.124527 -0.438547 -0.495788  0.531719  ... -0.344783 -0.716900
        1     0.839891  0.457642  0.740476  0.294743  ...  0.486457 -0.397130
        1     1.307910  0.582207  0.767343 -0.336605  ...  0.378708 -0.462378
        1     0.536907  0.838103 -0.232037 -0.030501  ... -0.066222 -0.281608
        1     0.103799  0.100242  0.188585 -0.071895  ...  0.086187  0.377087
        1     1.292545  1.251446  0.797103  1.138933  ...  0.246449 -0.122434
        1     0.167807  0.617943  0.033192 -0.035510  ...  0.255738 -0.199432
        1     0.626055  0.721879  0.526318  0.442115  ...  0.047542  0.713247
        1     0.572596  1.003392  0.264308  0.693211  ... -0.007411  0.293116
        1     0.902861  0.860574  0.500085  0.434529  ...  0.005157  0.466946
        1     0.238696  0.922097  0.403750  0.085171  ...  0.099539  0.458106
        1     0.139980  0.411690 -0.063281 -0.667654  ...  0.231283 -0.585760
        1     0.129976  0.283047  0.408663  0.053961  ...  0.122588 -0.477742
        1     0.482717  1.315020  0.705061  1.216794  ... -0.289455  0.836124
        1     0.848169  1.571564  0.249938 -0.035098  ...  0.290107  0.302610
        1    -0.135219  0.302950 -0.540559 -0.054164  ... -0.091205 -0.208684
        1    -0.290886  0.110245 -0.414662 -0.576177  ...  0.240162 -0.409217
        1     1.533426  1.691619  0.668504  0.789031  ...  0.030807  0.466425
        1     0.979212  0.793255  0.558673  0.195374  ...  0.461860  0.033971
        1     1.374066  1.221540  1.178548  0.507174  ... -0.531032  1.036347
        1     1.075761  0.948254  0.497569  0.793175  ...  0.477977  0.199087
        1     1.538939  1.500364  0.679891  1.161522  ...  0.131325  0.234495
        1     0.393829 -0.186367  0.103257  0.505600  ...  0.546215 -0.570804
        1     0.513755  1.130534 -0.107944 -0.356172  ... -0.185074 -0.829860
        1     0.050273 -0.169620  0.100836  0.257339  ... -0.246112 -0.278171
        1     0.441319  0.720016  0.425210  0.762542  ...  0.488651  0.902739
        1     1.037876  1.126293  0.998697 -0.017834  ...  0.090991  0.562362
        1     1.918197  2.647520  0.893716  1.105520  ...  0.349113  0.631605
        1     1.130447  1.927525  0.903333  0.948476  ...  0.546170  0.719761
        1     1.164084  1.665436  0.538956  0.258288  ...  0.325784  0.467561
        1     0.469500  0.774152  0.578296  0.589506  ...  0.603329  0.332787
        1     0.149903  0.689648 -0.281025 -0.469851  ... -0.069206 -0.436296
        1     0.841626  1.224858  0.565990 -0.257098  ... -0.201929 -0.522436
        1     0.025307  0.352143  0.123425 -0.221280  ... -0.214636  0.186789
        1     0.730574  1.032669  0.375033  0.332584  ... -0.032237 -0.484842
        1     0.164615 -0.129867  0.411087  0.466709  ...  0.471722  0.421436
        1     0.959999  0.909643  0.805587  1.070830  ...  0.306278  0.636149
        1     0.278407  0.518814 -0.078187  0.480341  ...  0.546444  0.287434
        1     1.526314  1.892131  0.507588  1.053520  ...  0.435316 -0.385636
        1     0.616797  0.689063  0.433877  0.242678  ... -0.396291 -0.547378
        1     0.712696  0.665547  0.659205  0.035645  ...  0.336915  0.226694
        1     0.043574  0.615369  0.141361 -0.581474  ... -0.483335 -0.083721
        1     0.222655  0.709721  0.227211 -0.548572  ... -0.447491 -0.637043
        1     0.570261  1.535713  0.323032  0.490543  ... -0.104392  0.237783
        1     1.084991  1.183558  0.423464  0.810745  ...  0.577797  0.581262
        1    -0.392536  0.053829 -0.113933  0.964532  ...  0.451655  0.671013
        1     0.095597  0.177026 -0.465466  0.742609  ...  0.245170  0.928630
        1    -0.049695 -0.358310 -0.409342 -0.119785  ... -0.363250 -0.558264
        1     0.577573  0.628467  0.163830 -1.352972  ... -0.244407 -1.095182
        1     0.666876  1.084952  0.763765  0.685478  ...  0.434935  0.273486
        1     0.715738  0.788620  0.084446  0.850207  ... -0.071890 -0.089331
        1     0.577990  0.757483  0.446531  0.270415  ...  0.106290 -0.138409
        1     1.089985  1.193974  0.751040  0.414795  ...  0.288204  0.550798
        1     0.904081  1.119761  0.922571  0.127440  ...  0.536911  0.209576
        1     0.442216  0.889439  1.098826  0.574328  ...  0.435776 -0.028021
        1     0.837893  0.654560  0.611379  1.058052  ...  0.965792  0.678457

                   455       679       488       464       469       320  \
session run2
1       1     0.736108 -0.051251  0.594861  0.672498  0.121565 -0.007170
        1     0.465060 -0.467582  0.295684  0.253646  0.130659  0.116119
        1     0.519986 -0.289370  0.095269  0.517961  0.255854 -0.184879
        1     0.836529 -0.063920  0.695921  0.868462  0.298080  0.417460
        1    -0.312576  0.112980 -0.142473 -0.289536  0.693231 -0.066720
        1     0.693426  0.320551  0.391701  0.765216  0.626872  0.329643
        1     0.054324  0.639537  0.593228 -0.048650  0.274247 -0.140620
        1     0.208005 -0.144569 -0.030557  0.262995 -0.042284 -0.118904
        1     0.337395 -0.108562  0.221295  0.284066  0.343713  0.035350
        1     0.574169  0.233179  0.196628  0.446480  0.083955  0.230184
        1    -0.024251  0.379944 -0.216000 -0.030412  0.522949 -0.173711
        1     0.325146  0.536477  0.498518  0.187931  0.051416  0.080687
        1     0.520822  0.067046  0.359244  0.508089  0.334057  0.452321
        1     0.168805  0.098629  0.549286  0.275834  0.067715  0.015900
        1     0.881281  0.331900  0.536821  0.834359  0.703286  0.518138
        1    -0.033270 -0.172639  0.271604 -0.053171  0.482380  0.100698
        1     0.139930 -0.001271  0.512307  0.176850  0.151389 -0.266040
        1    -0.359073  0.350755 -0.192150 -0.471483 -0.090825  0.257550
        1     0.514408  0.809099  0.481864  0.677689  0.764297  0.406017
        1    -0.478588  0.233542 -0.027364 -0.622182  0.627534  0.092701
        1    -0.139511 -0.265819 -0.226763 -0.184428  0.171247 -0.324298
        1     0.982428 -0.111692  0.692970  0.864592  0.257770  0.238966
        1     0.504773 -0.049835  0.175271  0.406461  0.615787  0.180449
        1    -0.388072  0.557042  0.822343 -0.050306  0.212667 -0.010873
        1     0.665862  0.622750  0.434423  0.462535  0.384838  0.491731
        1     0.996408  0.436185  0.201823  0.879176  1.221980  0.658396
        1     0.440769 -0.104790  0.046256  0.266503  0.721894  0.177872
        1     0.158685 -0.154998  0.168368  0.182783  0.148484 -0.069666
        1    -1.009611  0.448876  0.081228 -0.878096  0.266118  0.172492
        1     0.505425  1.190275  0.154685  0.573089  0.208515  0.064354
        1     0.265150 -0.329342  0.883365  0.225687  0.134832  0.041160
        1     0.586313  0.216329  0.644771  0.660175  0.527269  0.334637
        1     0.935290  0.065941  0.571768  0.899190  0.344221  0.545511
        1     0.605310  0.314697  0.549643  0.645584  0.088913  0.916741
        1     0.990390 -0.115629  0.768294  0.761680  0.575762  0.566783
        1    -0.677494  0.144548 -0.160145 -0.785633 -0.023274 -0.044629
        1     0.407930  0.431758  0.199974  0.340795  0.672972  0.027659
        1    -0.389688  0.394442  0.163389 -0.238461  0.317073 -0.499899
        1     0.040002  0.576991  0.316667  0.162363  0.379490  0.134780
        1     0.607101  0.359071  0.339197  0.537685  0.669337  0.350246
        1     0.746314  0.332992  0.840059  0.674919  0.615040  0.667414
        1     0.253401 -0.016406 -0.026721  0.095085  0.824002  0.136016
        1     0.330002  0.363685  0.156759  0.450398  0.912994  0.563270
        1     0.134453  0.145001  0.145306 -0.022508 -0.098088  0.079245
        1     0.488702  0.386322  0.772525  0.500044  0.848892  0.083081
        1    -0.047644  0.484300  0.172848 -0.141835 -0.254087  0.303162
        1    -0.166337  0.921090  0.345629 -0.182959 -0.069741 -0.307232
        1     0.862040  1.121560  0.474552  0.719599  0.295827  0.296168
        1     0.598365  0.453079  0.372347  0.535727  0.233946  0.362625
        1     0.655302 -0.087058 -0.177891  0.553372  0.460946  0.113064
        1    -0.049198 -0.187937  0.058847 -0.083425  0.377291  0.461606
        1    -0.305613 -0.003496 -0.030570 -0.263780  0.173946  0.032234
        1    -0.812260  0.523445 -0.075910 -0.770968  0.078722 -0.285787
        1     0.414624  0.244211  0.735261  0.391203  0.540868 -0.001710
        1     0.117460 -0.001867 -0.105129 -0.018472  0.260346  0.432249
        1     0.237544 -0.066132  0.249186  0.419606  0.651323 -0.031869
        1     0.884927  0.663045  0.805282  0.990351  0.805397  0.519801
        1     0.321315 -0.207385  0.685219  0.397963  0.629548  0.018727
        1     0.457901  0.443504  0.501441  0.302575  0.736905  0.338959
        1     1.144621  0.474261  0.454950  1.139187  0.712163  0.644738

                   456       475
session run2
1       1     0.706152  0.016536
        1     0.955649  0.681669
        1     1.047017  0.769227
        1     1.143668  0.063449
        1    -0.219672  0.508826
        1     1.127465  0.808010
        1     0.279986  0.703122
        1     0.577896  0.327956
        1     0.644397  0.462944
        1     1.195935  0.662540
        1     0.011706  0.237345
        1     0.507864  0.556166
        1     0.041843  0.565720
        1     0.432351  0.198372
        1     1.223202  0.491846
        1     0.031639  0.134528
        1     0.268239  0.115514
        1     0.210292 -0.270670
        1     0.277349  0.509985
        1    -0.261055  0.767813
        1     0.593984  0.713454
        1     0.999146  0.268205
        1     1.263856  0.919076
        1    -0.713484  0.236973
        1     1.138291  0.256026
        1     1.502028  0.365513
        1     1.106130  0.608414
        1     0.525481  0.688328
        1    -0.322076 -0.150941
        1     0.146714  0.662192
        1     0.710014  0.076232
        1     1.054464  0.733046
        1     1.407937  0.580794
        1     0.669210  0.302626
        1     1.553660  0.543778
        1    -0.622739  0.382807
        1    -0.079814  0.543666
        1    -0.258484  0.167718
        1     0.116182  0.331022
        1     1.131144  0.570033
        1     1.268970 -0.027005
        1     1.052971  0.378815
        1     0.556450  0.423619
        1     0.134132  0.423323
        1     0.798832  0.482897
        1    -0.326593  0.468845
        1    -0.419215  0.061103
        1     0.866419 -0.172873
        1     1.011710  0.761239
        1     1.396247 -0.133294
        1     0.617259  0.753008
        1    -0.583025  0.683596
        1    -1.071888  0.109857
        1     0.733170  0.041992
        1     0.484869  0.752751
        1     0.222134 -0.017222
        1     1.182532  0.225368
        1     0.403571  0.123026
        1     1.110105  0.586749
        1     1.897686 -0.267343

[60 rows x 100 columns]

NameError: name 'pdf' is not defined

In [8]:
train_paradigm

                 x  range
session run2
1       2     11.0    0.0
        2     18.0    0.0
        2     24.0    0.0
        2     17.0    0.0
        2     17.0    0.0
...            ...    ...
2       4     12.0    0.0
        4     13.0    0.0
        4     18.0    0.0
        4     14.0    0.0
        4     17.0    0.0

[420 rows x 2 columns]

In [7]:
train_paradigm

                 x  range
session run2
1       2     11.0    0.0
        2     18.0    0.0
        2     24.0    0.0
        2     17.0    0.0
        2     17.0    0.0
...            ...    ...
2       4     12.0    0.0
        4     13.0    0.0
        4     18.0    0.0
        4     14.0    0.0
        4     17.0    0.0

[420 rows x 2 columns]

In [14]:
pdfs

dim_0             10.0                11.0                12.0            \
dim_1              0.0       1.0       0.0       1.0       0.0       1.0
session run2
1       1     0.000053  0.000043  0.000027  0.000027  0.000024  0.000031
        1     0.004676  0.009441  0.026461  0.059301  0.074684  0.190549
        1     0.004421  0.003171  0.021441  0.015327  0.063932  0.046268
        1     0.246172  0.385067  0.735707  1.000000  0.790908  0.877924
        1     0.871138  0.483812  1.000000  0.516471  0.821254  0.386863
...                ...       ...       ...       ...       ...       ...
2       4     0.090663  0.046281  0.206838  0.168466  0.332732  0.394508
        4     1.000000  0.091802  0.573700  0.076577  0.292182  0.050244
        4     0.001600  0.005150  0.000283  0.000602  0.000100  0.000128
        4     0.024651  0.055710  0.039440  0.082351  0.055373  0.091391
        4     0.003895  0.018007  0.030255  0.154539  0.110313  0.492384

dim_0             13.0                14.0            ...          36.0  \
dim_1              0.0       1.0       0.0       1.0  ...           0.0
session run2                                          ...
1       1     0.000033  0.000059  0.000057  0.000148  ...  1.079455e-03
        1     0.135872  0.408590  0.180236  0.664895  ...  4.197298e-07
        1     0.146558  0.107710  0.281081  0.208831  ...  2.337745e-06
        1     0.493599  0.431255  0.236407  0.159324  ...  1.816075e-04
        1     0.590220  0.246711  0.409236  0.147076  ...  4.177695e-08
...                ...       ...       ...       ...  ...           ...
2       4     0.426787  0.670007  0.468062  0.896203  ...  4.483311e-01
        4     0.170598  0.035706  0.120531  0.030447  ...  5.370385e-02
        4     0.000066  0.000051  0.000070  0.000034  ...  2.591616e-01
        4     0.075791  0.092224  0.104676  0.093242  ...  1.035864e-01
        4     0.247035  0.843705  0.401927  1.000000  ...  8.522950e-05

dim_0                               37.0                        38.0  \
dim_1                  1.0           0.0           1.0           0.0
session run2
1       1     3.781595e-02  9.007633e-04  3.432375e-02  7.600480e-04
        1     9.366835e-07  2.456907e-07  5.571727e-07  1.476045e-07
        1     5.622248e-05  2.007681e-06  4.805223e-05  1.760131e-06
        1     1.966091e-02  1.653681e-04  1.910667e-02  1.525048e-04
        1     2.389388e-06  3.394370e-08  1.965787e-06  2.827331e-08
...                    ...           ...           ...           ...
2       4     7.219455e-01  4.775228e-01  7.909806e-01  5.067096e-01
        4     9.324012e-01  4.814900e-02  8.794588e-01  4.298828e-02
        4     9.928768e-01  2.520153e-01  1.000000e+00  2.425235e-01
        4     4.434239e-02  8.520330e-02  3.645252e-02  7.019870e-02
        4     7.377462e-05  7.466134e-05  6.384563e-05  6.578392e-05

dim_0                               39.0                        40.0  \
dim_1                  1.0           0.0           1.0           0.0
session run2
1       1     3.063597e-02  6.488846e-04  2.693527e-02  5.607065e-04
        1     3.396690e-07  9.091431e-08  2.120670e-07  5.734419e-08
        1     4.101041e-05  1.574405e-06  3.496477e-05  1.435767e-06
        1     1.806969e-02  1.426085e-04  1.667022e-02  1.353118e-04
        1     1.615064e-06  2.411748e-08  1.325438e-06  2.104527e-08
...                    ...           ...           ...           ...
2       4     8.605491e-01  5.359806e-01  9.303192e-01  5.653746e-01
        4     8.184959e-01  3.826725e-02  7.532058e-01  3.399849e-02
        4     9.881913e-01  2.314140e-01  9.607739e-01  2.192974e-01
        4     3.015433e-02  5.795042e-02  2.510585e-02  4.794446e-02
        4     5.565997e-05  5.827243e-05  4.885887e-05  5.187684e-05

dim_0
dim_1                  1.0
session run2
1       1     2.336466e-02
        1     1.354847e-07
        1     2.979627e-05
        1     1.503778e-02
        1     1.086937e-06
...                    ...
2       4     1.000000e+00
        4     6.865451e-01
        4     9.212713e-01
        4     2.103891e-02
        4     4.316519e-05

[240 rows x 124 columns]