In [44]:
import pandas as pd
from pathlib import Path

bids_folder = Path('/data/ds-neuralpriors')

df = pd.read_csv(bids_folder / 'participants.tsv', sep='\t')

# Number of females, mean age, age range
num_females = df[df['Sex'] == 'F'].shape[0]
mean_age = df['age'].mean()
age_range = df['age'].min(), df['age'].max()
# Print the results
print('Total number of participants:', df.shape[0])
print(f"Number of females: {num_females}")
print(f"Mean age: {mean_age}")
print(f"Age range: {age_range}")

Total number of participants: 39
Number of females: 13
Mean age: 23.102564102564102
Age range: (18.0, 34.0)

In [42]:
import pandas as pd


from neural_priors.utils.data import get_all_subject_ids

subject_ids = [int(s) for s in get_all_subject_ids()]

fn = '/Users/gdehol/Downloads/participants.csv'
df = pd.read_csv(fn, header=1, usecols=[0, 1,2,3], index_col=0)

# Drop the first row
df = df.iloc[1:]

df.index.name = 'participant_id'

# Drop all row where index is nan
df = df.loc[df.index.notna()]

df.index = df.index.astype(int)
df = df.loc[subject_ids]
df = df.rename(columns={
    'Age':'age', 'Gender':'Sex'}).drop('Name', axis=1)


df.to_csv('/data/ds-neuralpriors/participants.tsv', sep='\t')

In [27]:
df

                                    Name   Age Gender
subject_id
1                           Jana Horbach  20.0      F
2                       Julian Chariatte  22.0      M
3                          Zhao Qingzhou  30.0      M
4                      Alexander Staikov  22.0      M
5                                 Nan Li  25.0      F
6                          Tomasso Guida  21.0      M
7                       Dmitrii Gavrilov  34.0      M
8                           Janna Blaume  23.0      F
9                        Yannick Brunner  24.0      M
10                           Selin Göksu  20.0      F
11                     Anna Poroshenkova  19.0      F
12                     Gabriel Tavernini  22.0      M
13                           Georg Henke  23.0      M
14                     Serafina Loessner  21.0      F
15                         Zhara Elenska  20.0      F
16                        Alessio Crotta  24.0      M
17                                Qi Guo  30.0      F
18                           Jeremy Cook  27.0      M
19                             Thomas Li  18.0      M
20                            Linus Joos  26.0      M
21                         Maria Aarting  20.0      F
22                      Thomas Baptistal  23.0      M
23                        Mariya Mollova  23.0      F
24          Alma Lorena Rodriguez Curiel  24.0      F
25                            Yuchen Pan  23.0      M
26                     Roger Akram Bregy  21.0      M
27                        Savindu Herath  31.0      M
28                     Nicolas Armbrusks  25.0      M
29                   Amelie Tolstorukova  19.0      F
30                 Spyridon Garyfallidis  30.0      M
31                         Utku Yesilova  21.0      M
32                           Shiyi Zhang  22.0      F
33                    Linus Gödickemeier  19.0      M
34                           David Ulloa  21.0      M
35                          Janos Keller  20.0      M
36                   Annamaria Ćernakova  18.0      F
37                          Henri Putman  22.0      M
38                       Yannic Gretener  20.0      M
39                       Lars Niedermann  21.0      M
40                         Tim Leonhardt  20.0      M
41                         Kristi Padrón  29.0      F
42                Maria Beatrice Bianchi  23.0      F
NaN                                  NaN   NaN    NaN
NaN                                  NaN  23.0     16
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN

In [22]:
df

                                    Name   Age Gender
subject_id
1                           Jana Horbach  20.0      F
2                       Julian Chariatte  22.0      M
3                          Zhao Qingzhou  30.0      M
4                      Alexander Staikov  22.0      M
5                                 Nan Li  25.0      F
6                          Tomasso Guida  21.0      M
7                       Dmitrii Gavrilov  34.0      M
8                           Janna Blaume  23.0      F
9                        Yannick Brunner  24.0      M
10                           Selin Göksu  20.0      F
11                     Anna Poroshenkova  19.0      F
12                     Gabriel Tavernini  22.0      M
13                           Georg Henke  23.0      M
14                     Serafina Loessner  21.0      F
15                         Zhara Elenska  20.0      F
16                        Alessio Crotta  24.0      M
17                                Qi Guo  30.0      F
18                           Jeremy Cook  27.0      M
19                             Thomas Li  18.0      M
20                            Linus Joos  26.0      M
21                         Maria Aarting  20.0      F
22                      Thomas Baptistal  23.0      M
23                        Mariya Mollova  23.0      F
24          Alma Lorena Rodriguez Curiel  24.0      F
25                            Yuchen Pan  23.0      M
26                     Roger Akram Bregy  21.0      M
27                        Savindu Herath  31.0      M
28                     Nicolas Armbrusks  25.0      M
29                   Amelie Tolstorukova  19.0      F
30                 Spyridon Garyfallidis  30.0      M
31                         Utku Yesilova  21.0      M
32                           Shiyi Zhang  22.0      F
33                    Linus Gödickemeier  19.0      M
34                           David Ulloa  21.0      M
35                          Janos Keller  20.0      M
36                   Annamaria Ćernakova  18.0      F
37                          Henri Putman  22.0      M
38                       Yannic Gretener  20.0      M
39                       Lars Niedermann  21.0      M
40                         Tim Leonhardt  20.0      M
41                         Kristi Padrón  29.0      F
42                Maria Beatrice Bianchi  23.0      F
NaN                                  NaN   NaN    NaN
NaN                                  NaN  23.0     16
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN
NaN                                  NaN   NaN    NaN

In [23]:
subject_ids

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41]

,Unnamed: 0,Name,Age,Gender,Session 1,Unnamed: 5,Unnamed: 6,Unnamed: 7,Session 2,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Subject,NaN,NaN,NaN,Date,Order,Payoff,Notes,Date,Order,...,+Hourly rate,Paid,Payment batch,Batch 1,Batch 2,NaN,NaN,NaN,NaN,NaN
1,1,Jana Horbach,20.0,F,15/04/2024,Narrow First,CHF26.06,Old payment scheme,26/4/2024,Wide First,...,CHF154.37,154,1,154,0,NaN,NaN,NaN,NaN,NaN
2,2,Julian Chariatte,22.0,M,18/04/2024,Wide first,CHF12.95,NaN,25/04/2024,Narrow First,...,CHF128.02,128,1,128,0,NaN,NaN,NaN,NaN,NaN
3,3,Zhao Qingzhou,30.0,M,22/04/2024,Narrow First,CHF10.44,NaN,29/04/2024,Wide First,...,CHF123.11,123,1,123,0,NaN,NaN,NaN,NaN,NaN
4,4,Alexander Staikov,22.0,M,22/04/2024,Wide first,CHF13.61,NaN,29/04/2024,Narrow First,...,CHF128.63,129,1,129,0,NaN,NaN,NaN,NaN,NaN
5,5,Nan Li,25.0,F,23/04/2024,Narrow First,CHF13.01,NaN,30/04/2024,Wide First,...,CHF128.02,128,1,128,0,NaN,NaN,NaN,NaN,NaN
6,6,Tomasso Guida,21.0,M,23/04/2024,Wide first,CHF16.97,Cursors was off the screen for few seconds dur...,30/04/2024,Narrow First,...,CHF134.08,134,1,134,0,NaN,NaN,NaN,NaN,NaN
7,7,Dmitrii Gavrilov,34.0,M,23/04/2024,Narrow first,CHF15.63,NaN,30/04/2024,Wide First,...,CHF133.42,133,1,133,0,NaN,NaN,NaN,NaN,NaN
8,8,Janna Blaume,23.0,F,24/04/2024,Wide first,CHF12.11,Problems with heart rate monitor,07/05/2024,Narrow First,...,CHF124.30,124,1,124,0,NaN,NaN,NaN,NaN,NaN
9,9,Yannick Brunner,24.0,M,26/04/2024,Narrow first,CHF12.74,NaN,03/05/2024,Wide First,...,CHF126.68,127,1,127,0,NaN,NaN,NaN,NaN,NaN
10,10,Selin Göksu,20.0,F,26/04/2024,Wide first,CHF14.31,NaN,03/05/2024,Narrow First,...,CHF130.45,130,1,130,0,NaN,NaN,NaN,NaN,NaN
11,11,Anna Poroshenkova,19.0,F,06/05/2024,Narrow first,CHF13.52,NaN,Cancelled,NaN,...,CHF63.52,64,2,0,64,v,NaN,NaN,NaN,NaN
12,12,Gabriel Tavernini,22.0,M,06/05/2024,Wide first,CHF14.95,NaN,13/05/2024,Narrow First,...,CHF131.37,131,1,131,0,NaN,NaN,NaN,NaN,NaN
13,13,Georg Henke,23.0,M,06/05/2024,Narrow first,CHF17.57,NaN,13/05/2024,Wide First,...,CHF136.00,136,1,136,0,NaN,NaN,NaN,NaN,NaN
14,14,Serafina Loessner,21.0,F,06/05/2024,Wide first,CHF16.51,NaN,13/05/2024,Narrow First,...,CHF133.56,134,1,134,0,NaN,NaN,NaN,NaN,NaN
15,15,Zhara Elenska,20.0,F,07/05/2024,Narrow first,CHF16.62,NaN,14/05/2024,Wide First,...,CHF134.49,138,1,138,0,NaN,NaN,NaN,NaN,NaN
16,16,Alessio Crotta,24.0,M,07/05/2024,Wide first,CHF15.85,NaN,14/05/2024,Narrow First,...,CHF129.92,130,1,130,0,NaN,NaN,NaN,NaN,NaN
17,17,Qi Guo,30.0,F,07/05/2024,Narrow first,CHF11.28,NaN,14/05/2024,Wide First,...,CHF124.87,125,1,125,0,NaN,NaN,NaN,NaN,NaN
18,18,Jeremy Cook,27.0,M,07/05/2024,Wide first,CHF11.89,NaN,14/05/2024,Narrow First,...,CHF127.28,127,1,127,0,NaN,NaN,NaN,NaN,NaN
19,19,Thomas Li,18.0,M,08/05/2024,Narrow first,CHF16.32,NaN,14/05/2024,Wide First,...,CHF134.31,134,1,134,0,NaN,NaN,NaN,NaN,NaN
20,20,Linus Joos,26.0,M,08/05/2024,Wide first,CHF13.64,NaN,15/05/2024,Narrow First,...,CHF129.81,140,1,140,0,NaN,NaN,NaN,NaN,NaN
21,21,Maria Aarting,20.0,F,08/05/2024,Narrow first,CHF15.62,NaN,15/05/2024,Wide First,...,CHF132.45,137,1,137,0,NaN,NaN,5.0,2.0,10.0
22,22,Thomas Baptistal,23.0,M,10/05/2024,Wide first,CHF16.60,NaN,17/05/2024,Narrow First,...,CHF133.38,133,2,0,133,v,NaN,2.0,12.0,24.0
23,23,Mariya Mollova,23.0,F,10/05/2024,Narrow first,CHF12.63,NaN,Cancelled,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,1.0,36.0,36.0
24,24,Alma Lorena Rodriguez Curiel,24.0,F,10/05/2024,Wide first,CHF11.52,NaN,17/05/2024,Narrow First,...,CHF119.98,120,2,0,120,v,NaN,NaN,NaN,70.0
25,25,Yuchen Pan,23.0,M,21/05/2024,Narrow first,CHF16.84,NaN,28/05/2024,Wide First,...,CHF131.38,131,2,0,131,v,NaN,NaN,NaN,NaN
26,26,Roger Akram Bregy,21.0,M,21/05/2024,Wide first,CHF16.60,NaN,28/05/2024,Narrow First,...,CHF132.07,132,2,0,132,v,NaN,NaN,NaN,NaN
27,27,Savindu Herath,31.0,M,21/05/2024,Narrow first,CHF15.75,NaN,28/05/2024,Wide First,...,CHF129.82,130,2,0,130,v,NaN,NaN,NaN,NaN
28,28,Nicolas Armbrusks,25.0,M,22/05/2024,Wide first,CHF13.79,NaN,29/05/2024,Narrow First,...,CHF130.03,130,2,0,130,v,NaN,NaN,NaN,NaN
29,29,Amelie Tolstorukova,19.0,F,22/05/2024,Narrow first,CHF15.24,NaN,29/05/2024,Wide First,...,CHF130.00,130,2,0,130,v,NaN,NaN,NaN,NaN
30,30,Spyridon Garyfallidis,30.0,M,22/05/2024,Wide first,CHF15.62,NaN,29/05/2024,Narrow First,...,CHF131.57,132,2,0,132,v,NaN,NaN,NaN,NaN
31,31,Utku Yesilova,21.0,M,23/05/2024,Narrow first,CHF13.58,Did three T1 scans. The third one is the best....,NaN,NaN,...,CHF127.09,127,2,0,127,v,NaN,NaN,NaN,NaN
32,32,Shiyi Zhang,22.0,F,23/05/2024,Wide first,CHF7.07,NaN,30/05/2024,Narrow First,...,CHF120.73,121,2,0,121,v,NaN,NaN,NaN,NaN
33,33,Linus Gödickemeier,19.0,M,23/05/2024,Narrow first,CHF13.46,NaN,30/05/2024,Wide First,...,CHF128.85,129,2,0,129,v,NaN,NaN,NaN,NaN
34,34,David Ulloa,21.0,M,23/05/2024,Wide first,CHF10.27,NaN,30/05/2024,Narrow First,...,CHF125.90,126,2,0,126,v,NaN,NaN,NaN,NaN
35,35,Janos Keller,20.0,M,24/05/2024,Narrow first,CHF15.84,NaN,31/05/2024,Wide first,...,CHF131.65,132,2,0,132,v,NaN,NaN,NaN,NaN
36,36,Annamaria Ćernakova,18.0,F,24/05/2024,Wide first,CHF14.06,NaN,31/05/2024,Narrow first,...,CHF128.21,128,2,0,128,v,NaN,NaN,NaN,NaN
37,37,Henri Putman,22.0,M,24/05/2024,Narrow first,CHF12.51,NaN,31/05/2024,Wide first,...,CHF126.38,126,2,0,126,v,NaN,NaN,NaN,NaN
38,38,Yannic Gretener,20.0,M,24/05/2024,Wide first,CHF14.36,NaN,31/05/2024,Narrow first,...,CHF129.62,130,2,0,130,v,NaN,NaN,NaN,NaN
39,39,Lars Niedermann,21.0,M,27/05/2024,Narrow first,CHF16.73,NaN,03/06/2024,Wide first,...,CHF133.38,133,2,0,133,v,NaN,NaN,NaN,NaN
40,40,Tim Leonhardt,20.0,M,27/05/2024,Wide first,CHF16.98,NaN,03/06/2024,Narrow first,...,CHF134.11,134,2,0,134,v,NaN,NaN,NaN,NaN
41,41,Kristi Padrón,29.0,F,27/05/2024,Narrow first,CHF14.66,NaN,03/06/2024,Wide first,...,CHF127.79,128,2,NaN,128,v,NaN,NaN,NaN,NaN
42,42,Maria Beatrice Bianchi,23.0,F,DID NOT SCAN,NaN,CHF20.00,Piercing,NaN,NaN,...,NaN,20,2,NaN,20,v,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,23.0,16,NaN,NaN,CHF14.24,NaN,NaN,NaN,...,NaN,NaN,Paid,2642,2536,5178,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,2.273372269,NaN,NaN,NaN,...,NaN,NaN,Brought back,138,70,208,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1600,2600,3200,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-6,-2186,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,100,7,700,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20,2,40,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,coins big,NaN,100,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,coins medium,NaN,30,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,coins small,NaN,6,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,876,NaN,NaN,NaN,NaN